"use client";

import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3 } from "lucide-react";
import { useState } from "react";
import type { StarterRecord, StarterWeekRecord } from "@/lib/record-types";
import { cn } from "@/lib/utils";
import { RecordSectionView } from "@/components/starter/record-section";

const accentByWeek = ["bg-coral", "bg-yellow", "bg-blue", "bg-green", "bg-violet"];

function PageContent({ week }: { week: StarterWeekRecord }) {
  return <div key={week.id} className="book-page-in mx-auto max-w-3xl space-y-6 sm:space-y-7"><div className="flex items-end justify-between gap-4 border-b border-ink/10 pb-5 sm:gap-5"><div className="min-w-0"><p className="font-mono text-[10px] font-bold tracking-[0.16em] text-coral sm:text-xs sm:tracking-[0.18em]">CHAPTER {String(week.week).padStart(2, "0")}</p><h2 className="mt-2 break-keep font-display text-[clamp(2rem,9vw,3rem)] font-black leading-tight tracking-[-0.07em] sm:text-5xl">{week.title}</h2></div><span className={cn("grid size-10 shrink-0 place-items-center rounded-xl text-lg font-black sm:size-12 sm:rounded-2xl sm:text-xl", accentByWeek[week.week - 1], week.week === 2 ? "text-ink" : "text-paper")}>{week.week}</span></div><p className="text-sm font-semibold text-muted">{week.status === "complete" ? "이 주차에 남긴 기록" : week.status === "missing" ? "기록이 비어 있는 주차" : "다음 페이지에서 이어질 기록"}</p><div className="space-y-4 sm:space-y-5">{week.sections.map((section) => <RecordSectionView key={section.id} section={section} />)}</div></div>;
}

export function BookReader({ record }: { record: StarterRecord }) {
  const [current, setCurrent] = useState(0);
  const week = record.weeks[current];
  const completed = record.weeks.filter((item) => item.status === "complete").length;
  const goTo = (next: number) => setCurrent(Math.max(0, Math.min(record.weeks.length - 1, next)));
  return <section className="mt-12 sm:mt-16"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between sm:gap-5"><div><p className="text-[10px] font-black tracking-[0.16em] text-coral sm:text-xs sm:tracking-[0.18em]">THE BOOK OF {record.name.toUpperCase()}</p><h2 className="mt-3 break-keep font-display text-[clamp(2.25rem,9vw,3rem)] font-black leading-tight tracking-[-0.06em] sm:text-5xl">나를 발견해온<br />시간의 페이지</h2></div><div className="flex items-center gap-2 text-xs font-semibold text-muted sm:text-sm"><BookOpen className="size-4 text-coral" /> {completed}/5 chapters collected</div></div><div className="mt-7 overflow-hidden rounded-[1.5rem] border border-ink/10 bg-[#fdf9f0] shadow-[6px_6px_0_#f6d26d] sm:mt-8 sm:rounded-[2rem] sm:shadow-[10px_10px_0_#f6d26d]"><div className="scrollbar-none flex gap-1.5 overflow-x-auto overscroll-x-contain border-b border-ink/10 bg-white/40 px-3 py-3 sm:gap-2 sm:px-6 sm:py-4">{record.weeks.map((item, index) => <button key={item.id} onClick={() => goTo(index)} aria-label={`${item.week}주차 ${item.title} 보기`} className={cn("flex min-h-11 shrink-0 items-center gap-1.5 rounded-full px-3 text-[13px] font-bold transition sm:gap-2 sm:px-4 sm:text-sm", current === index ? "bg-ink text-paper" : "text-muted hover:bg-ink/5")}><span className="font-mono text-[10px] sm:text-xs">0{item.week}</span><span className="max-w-[7.5rem] truncate sm:max-w-none">{item.title}</span><span className={cn("size-2 shrink-0 rounded-full", item.status === "complete" ? "bg-green" : "bg-ink/15")} /></button>)}</div><div className="relative min-h-[430px] p-4 sm:min-h-[520px] sm:p-10"><PageContent week={week} /></div><div className="flex items-center justify-between border-t border-ink/10 bg-white/35 px-4 py-3 sm:px-8 sm:py-4"><button onClick={() => goTo(current - 1)} disabled={current === 0} className="inline-flex min-h-11 items-center gap-1.5 rounded-full px-2 text-sm font-bold text-muted transition hover:bg-ink/5 hover:text-ink disabled:opacity-30 sm:gap-2 sm:px-3"><ArrowLeft className="size-4" /> 이전 장</button><span className="font-mono text-[11px] text-muted sm:text-xs">{String(current + 1).padStart(2, "0")} / 05</span><button onClick={() => goTo(current + 1)} disabled={current === record.weeks.length - 1} className="inline-flex min-h-11 items-center gap-1.5 rounded-full px-2 text-sm font-bold text-muted transition hover:bg-ink/5 hover:text-ink disabled:opacity-30 sm:gap-2 sm:px-3">다음 장 <ArrowRight className="size-4" /></button></div></div><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs font-semibold text-muted"><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-green" /> 작성된 주차 {completed}</span><span className="inline-flex items-center gap-1.5"><Clock3 className="size-3.5 text-coral" /> 아직 이어지는 주차 {5 - completed}</span></div></section>;
}
