import { Image as ImageIcon, Quote, Tags } from "lucide-react";
import type { RecordSection } from "@/lib/record-types";

export function RecordSectionView({ section }: { section: RecordSection }) {
  if (section.type === "pending") return <div className="rounded-[1.25rem] border border-dashed border-ink/20 bg-white/40 p-6 text-center sm:rounded-[1.5rem] sm:p-7"><p className="font-display text-xl font-black sm:text-2xl">{section.heading}</p><p className="mt-3 break-keep text-sm leading-7 text-muted sm:text-base">{section.body}</p></div>;
  if (section.type === "missing") return <div className="rounded-[1.25rem] bg-[#f1ebe0] p-6 sm:rounded-[1.5rem] sm:p-7"><p className="font-display text-xl font-black text-muted sm:text-2xl">{section.heading}</p><p className="mt-3 break-keep text-sm leading-7 text-muted sm:text-base">{section.body}</p></div>;
  if (section.type === "keywords") return <section className="rounded-[1.25rem] bg-yellow/35 p-5 sm:rounded-[1.5rem] sm:p-6"><div className="flex items-center gap-2 text-xs font-black tracking-[0.14em] text-ink"><Tags className="size-4" /> KEYWORDS</div><div className="mt-4 flex flex-wrap gap-2 sm:mt-5">{section.items?.map((item) => <span key={item} className="max-w-full break-keep rounded-full bg-paper px-3 py-2 text-xs font-semibold text-ink sm:text-sm">{item}</span>)}</div></section>;
  if (section.type === "media") return <section><div className="flex items-center gap-2 text-xs font-black tracking-[0.14em] text-coral"><ImageIcon className="size-4" /> ATTACHED MEMORIES</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{section.media?.map((media) => <a key={media.id} href={media.url} target="_blank" rel="noreferrer" className="group flex min-h-20 items-center gap-3 rounded-2xl border border-ink/10 bg-white/60 p-3 transition hover:-translate-y-0.5 hover:border-coral/40"><img src={media.url} alt={media.name} className="size-14 shrink-0 rounded-xl object-cover sm:size-16" /><span className="min-w-0 break-all text-xs font-semibold text-muted group-hover:text-coral sm:text-sm">{media.name}</span></a>)}</div></section>;
  return <section className="rounded-[1.25rem] border border-ink/10 bg-white/55 p-5 sm:rounded-[1.5rem] sm:p-7"><div className="flex items-start gap-3"><Quote className="mt-1 size-5 shrink-0 text-coral" /><div className="min-w-0 reading-copy"><h3 className="break-keep font-display text-xl font-black leading-tight tracking-[-0.04em] sm:text-2xl">{section.heading}</h3><div className="mt-5 space-y-5 text-base leading-8 text-ink/80 sm:text-[1.03rem]">{section.paragraphs?.map((paragraph, index) => <p key={`${section.id}-${index}`} className="whitespace-pre-line">{paragraph}</p>)}</div></div></div></section>;
}
